# Generated by Django 6.0.3 on 2026-04-01 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_student_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher__name', 'student__name'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'student'), name='unique_teacher_student_link')],
            },
        ),
    ]
