# Generated by Django 6.0.3 on 2026-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordernumber',
            field=models.CharField(blank=True, db_index=True, help_text='ERP order number', max_length=100),
        ),
    ]
