# Generated by Django 6.0.3 on 2026-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_ordernumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_spending_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to disable the soft spending warning.', max_digits=10, null=True)),
            ],
        ),
    ]
