# Generated by Django 6.0.3 on 2026-04-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('list_type', models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], max_length=20)),
            ],
            options={
                'ordering': ['store_name'],
            },
        ),
    ]
